baseURL = "http://www.chenaciousD.com"
languageCode = "en-us"
title = "Daniel Chen"
theme="archie"
copyright = "© Athul"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/chenaciousd/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/chenaciousd/"

[[params.social]]
name = "Email"
url = "mailto:daniel@chenaciousD.com"
icon = "mail"
# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3
